// 下行下发常用指令模板 (协议版本固定v2)
// param.type: uint32le | uint16le | uint8 | enum
// param.options: { key: label } 仅 type=enum 时有效
window.SK_DOWN_PRESETS = [
	{
		group: '指令操作 (0x11)',
		items: [
			{ name: '开业务猫', func: '0x11', desc: 'Tag93 开猫 仅业务',
				tlv: [{ tag: 93, items: [{ id: 0, value: [0x01] }] }] },
			{ name: '开维护猫', func: '0x11', desc: 'Tag93 开猫 仅维护',
				tlv: [{ tag: 93, items: [{ id: 0, value: [0x02] }] }] },
			{ name: '双开猫', func: '0x11', desc: 'Tag93 开猫 业务+维护',
				tlv: [{ tag: 93, items: [{ id: 0, value: [0x03] }] }] },
			{ name: '开阀', func: '0x11', desc: 'Tag93 阀门控制 开阀',
				tlv: [{ tag: 93, items: [{ id: 3, value: [0x01] }] }] },
			{ name: '关阀', func: '0x11', desc: 'Tag93 阀门控制 关阀',
				tlv: [{ tag: 93, items: [{ id: 3, value: [0x00] }] }] },
			{ name: '设备复位', func: '0x11', desc: 'Tag93 复位',
				param: { label: '延时(秒)', type: 'uint8', default: '2' },
				tlv: [{ tag: 93, items: [{ id: 1 }] }] },
			{ name: '初始化', func: '0x11', desc: 'Tag93 初始化',
				param: { label: '初始化类型', type: 'enum', default: '0', options: { 0: '数据初始化', 1: '参数初始化', 2: '恢复出厂', 3: '信息初始化' } },
				tlv: [{ tag: 93, items: [{ id: 2 }] }] },
		]
	},
	{
		group: '参数设置 (0x01)',
		items: [
			{ name: '设置计量底度', func: '0x01', desc: 'Tag3-ID17 计量底度(L)',
				param: { label: '底度(L)', type: 'uint32le', default: '0' },
				tlv: [{ tag: 3, items: [{ id: 17 }] }] },
			{ name: '设置上报频率', func: '0x01', desc: 'Tag3-ID9 上报频率(分钟) 须30整数倍',
				param: { label: '间隔(分钟)', type: 'uint16le', default: '30' },
				tlv: [{ tag: 3, items: [{ id: 9 }] }] },
			{ name: '设置维护平台上报频率', func: '0x01', desc: 'Tag3-ID22 维护后台上报频率(分钟) 须1440整数倍',
				param: { label: '间隔(分钟)', type: 'uint16le', default: '1440' },
				tlv: [{ tag: 3, items: [{ id: 22 }] }] },
			{ name: '设置采样间隔', func: '0x01', desc: 'Tag3-ID12 数据采样间隔(分钟)',
				param: { label: '间隔(分钟)', type: 'uint16le', default: '30' },
				tlv: [{ tag: 3, items: [{ id: 12 }] }] },
			{ name: '设置过流告警阈值', func: '0x01', desc: 'Tag3-ID0 过流告警(L/h)',
				param: { label: '阈值(L/h)', type: 'uint32le', default: '0' },
				tlv: [{ tag: 3, items: [{ id: 0 }] }] },
			{ name: '设置反流告警阈值', func: '0x01', desc: 'Tag3-ID2 反流告警(L/h)',
				param: { label: '阈值(L/h)', type: 'uint32le', default: '0' },
				tlv: [{ tag: 3, items: [{ id: 2 }] }] },
			{ name: '设置基准水量', func: '0x01', desc: 'Tag3-ID29 基准水量',
				param: { label: '基准水量', type: 'enum', default: '0', options: { 0: '1000L/圈', 1: '100L/圈', 2: '10L/圈', 3: '1L/圈' } },
				tlv: [{ tag: 3, items: [{ id: 29 }] }] },
			{ name: '设置采集方式', func: '0x01', desc: 'Tag3-ID24 采集方式',
				param: { label: '采集方式', type: 'enum', default: '5', options: { 0: '未知', 1: '数字状态', 2: '厚膜', 3: '光电', 4: '脉冲', 5: '无磁', 6: '超声波', 7: '电磁式', 8: '摄像', 9: '总线式', 10: '无磁摄像' } },
				tlv: [{ tag: 3, items: [{ id: 24 }] }] },
			{ name: '设置水表口径', func: '0x01', desc: 'Tag3-ID18 水表口径',
				param: { label: '口径', type: 'enum', default: '5', options: { 1: '15mm', 2: '20mm', 3: '25mm', 4: '32mm', 5: '40mm', 6: '50mm', 7: '65mm', 8: '80mm', 9: '100mm', 10: '125mm', 11: '150mm', 12: '200mm', 13: '250mm', 14: '300mm' } },
				tlv: [{ tag: 3, items: [{ id: 18 }] }] },
			{ name: '设置设备校时类型', func: '0x01', desc: 'Tag3-ID32 校时类型',
				param: { label: '校时类型', type: 'enum', default: '1', options: { 0: '基站校时', 1: '服务器校时' } },
				tlv: [{ tag: 3, items: [{ id: 32 }] }] },
			{ name: '设置设备启用标志', func: '0x01', desc: 'Tag3-ID31 启用标志',
				param: { label: '启用标志', type: 'enum', default: '1', options: { 0: '停止', 1: '启用', 2: '运输模式' } },
				tlv: [{ tag: 3, items: [{ id: 31 }] }] },
			{ name: '设置计量模组开关', func: '0x01', desc: 'Tag3-ID38 计量模组启用',
				param: { label: '开关', type: 'enum', default: '1', options: { 0: '关闭', 1: '开启' } },
				tlv: [{ tag: 3, items: [{ id: 38 }] }] },
			{ name: '配置业务平台IP', func: '0x01', desc: 'Tag3-ID6 服务器地址端口',
				param: { label: 'IP:端口', type: 'ascii', default: '', fillLen: 32 },
				tlv: [{ tag: 3, items: [{ id: 6 }] }] },
			{ name: '配置维护平台IP', func: '0x01', desc: 'Tag3-ID21 维护后台地址端口',
				param: { label: 'IP:端口', type: 'ascii', default: '', fillLen: 32 },
				tlv: [{ tag: 3, items: [{ id: 21 }] }] },
			{ name: '设置持续过流告警时间', func: '0x01', desc: 'Tag3-ID1 持续过流告警时间(分钟)',
				param: { label: '时间(分钟)', type: 'uint8', default: '30' },
				tlv: [{ tag: 3, items: [{ id: 1 }] }] },
			{ name: '设置持续反流告警时间', func: '0x01', desc: 'Tag3-ID3 持续反流告警时间(分钟)',
				param: { label: '时间(分钟)', type: 'uint8', default: '30' },
				tlv: [{ tag: 3, items: [{ id: 3 }] }] },
			{ name: '设置电压告警阈值', func: '0x01', desc: 'Tag3-ID4 电压告警阈值(0.01V)',
				param: { label: '阈值(0.01V)', type: 'uint16le', default: '0' },
				tlv: [{ tag: 3, items: [{ id: 4 }] }] },
			{ name: '配置APN', func: '0x01', desc: 'Tag3-ID7 APN信息',
				param: { label: 'APN', type: 'ascii', default: '', fillLen: 32 },
				tlv: [{ tag: 3, items: [{ id: 7 }] }] },
			{ name: '设置上报重发次数', func: '0x01', desc: 'Tag3-ID10 上报重发次数 0-4',
				param: { label: '次数', type: 'uint8', default: '1' },
				tlv: [{ tag: 3, items: [{ id: 10 }] }] },
			{ name: '设置上报重发间隔', func: '0x01', desc: 'Tag3-ID11 上报重发间隔(分钟)',
				param: { label: '间隔(分钟)', type: 'uint8', default: '20' },
				tlv: [{ tag: 3, items: [{ id: 11 }] }] },
			{ name: '设置密集采样起始时间', func: '0x01', desc: 'Tag3-ID14 密集数据采样起始时间(小时)',
				param: { label: '小时(0-23)', type: 'uint8', default: '0' },
				tlv: [{ tag: 3, items: [{ id: 14 }] }] },
			{ name: '设置密集采样间隔', func: '0x01', desc: 'Tag3-ID15 密集数据采样间隔(分钟) 须5整数倍',
				param: { label: '间隔(分钟)', type: 'uint8', default: '5' },
				tlv: [{ tag: 3, items: [{ id: 15 }] }] },
			{ name: '设置SN密钥', func: '0x01', desc: 'Tag3-ID16 SN密钥(ASCII)',
				param: { label: 'SN密钥', type: 'ascii', default: '', fillLen: 16 },
				tlv: [{ tag: 3, items: [{ id: 16 }] }] },
			{ name: '设置脉冲形式', func: '0x01', desc: 'Tag3-ID28 脉冲形式',
				param: { label: '脉冲形式', type: 'enum', default: '5', options: { 0: '未知', 1: '单脉冲', 2: '双脉冲', 3: '正反单脉冲', 4: '方向单脉冲', 5: 'HRI', 8: '三霍尔', 9: '双霍尔' } },
				tlv: [{ tag: 3, items: [{ id: 28 }] }] },
			{ name: '设置基表整数位数', func: '0x01', desc: 'Tag3-ID30 基表整数位数',
				param: { label: '整数位数', type: 'uint8', default: '5' },
				tlv: [{ tag: 3, items: [{ id: 30 }] }] },
			{ name: '设置机电分离状态', func: '0x01', desc: 'Tag3-ID34 机电分离状态配置',
				param: { label: '分离状态', type: 'enum', default: '0', options: { 0: '未分离', 1: '机电分离' } },
				tlv: [{ tag: 3, items: [{ id: 34 }] }] },
			{ name: '设置维护平台连接模式', func: '0x01', desc: 'Tag3-ID40 维护平台连接模式',
				param: { label: '连接模式', type: 'enum', default: '0', options: { 0: 'IPV4', 1: 'IPV6' } },
				tlv: [{ tag: 3, items: [{ id: 40 }] }] },
			{ name: '设置用水量功能超时', func: '0x01', desc: 'Tag3-ID41 用水量功能超时时间(秒) 0关闭',
				param: { label: '超时(秒)', type: 'uint16le', default: '0' },
				tlv: [{ tag: 3, items: [{ id: 41 }] }] },
			{ name: '设置用户表号(ASCII)', func: '0x01', desc: 'Tag3-ID42 用户表号(ASCII)',
				param: { label: '用户表号', type: 'ascii', default: '', fillLen: 20 },
				tlv: [{ tag: 3, items: [{ id: 42 }] }] },
			{ name: '设置基表号(ASCII)', func: '0x01', desc: 'Tag3-ID43 基表号(ASCII)',
				param: { label: '基表号', type: 'ascii', default: '', fillLen: 20 },
				tlv: [{ tag: 3, items: [{ id: 43 }] }] },
		]
	},
	{
		group: '信息查询 (0x03)',
		items: [
			{ name: '查询基础数据', func: '0x03', desc: 'Tag1 基础数据',
				tlv: [{ tag: 10, items: [{ id: 1 }] }] },
			{ name: '查询核心数据', func: '0x03', desc: 'Tag2 核心数据',
				tlv: [{ tag: 10, items: [{ id: 2 }] }] },
			{ name: '查询终端参数', func: '0x03', desc: 'Tag3 终端参数',
				tlv: [{ tag: 10, items: [{ id: 3 }] }] },
			{ name: '查询告警数据', func: '0x03', desc: 'Tag4 告警数据',
				tlv: [{ tag: 10, items: [{ id: 4 }] }] },
			{ name: '查询无磁传感器参数', func: '0x03', desc: 'Tag34 无磁传感器',
				tlv: [{ tag: 10, items: [{ id: 13 }] }] },
			{ name: '查询超声波表参数', func: '0x03', desc: 'Tag30 超声波表',
				tlv: [{ tag: 10, items: [{ id: 30 }] }] },
			{ name: '查询阀控参数', func: '0x03', desc: 'Tag36 阀控',
				tlv: [{ tag: 10, items: [{ id: 15 }] }] },
			{ name: '查询通信认证参数', func: '0x03', desc: 'Tag38 通信认证',
				tlv: [{ tag: 10, items: [{ id: 22 }] }] },
			{ name: '查询设备运行信息', func: '0x03', desc: 'Tag91 运行信息',
				tlv: [{ tag: 10, items: [{ id: 7 }] }] },
			{ name: '查询设备上行信息', func: '0x03', desc: 'Tag92 上行信息',
				tlv: [{ tag: 10, items: [{ id: 8 }] }] },
			{ name: '查询日结数据', func: '0x03', desc: 'Tag9 日结',
				tlv: [{ tag: 10, items: [{ id: 9 }] }] },
			{ name: '查询错误日志', func: '0x03', desc: 'Tag254 错误日志',
				tlv: [{ tag: 10, items: [{ id: 23 }] }] },
		]
	},
]
