// 下行下发常用指令模板 (协议版本固定v2)
// param.type: uint32le | uint16le | uint8 | enum | ascii
// param.options: { key: label } 仅 type=enum 时有效
window.SK_DOWN_PRESETS = [
	{
		group: '参数设置-业务平台配置 (0x01)',
		items: [
			{ name: '设置上报频率', func: '0x01', desc: 'Tag3-ID9 上报频率(分钟) 须30整数倍',
				param: { label: '间隔(分钟)', type: 'uint16le', default: '1440' },
				tlv: [{ tag: 3, items: [{ id: 9 }] }] },
			{ name: '配置业务平台IP', func: '0x01', desc: 'Tag3-ID6 服务器地址端口 ASCII 逗号分隔',
				param: { label: 'IP:端口', type: 'ascii', default: '', fillLen: 32 },
				tlv: [{ tag: 3, items: [{ id: 6 }] }] },
			{ name: '配置APN', func: '0x01', desc: 'Tag3-ID7 APN信息 ASCII',
				param: { label: 'APN', type: 'ascii', default: '', fillLen: 32 },
				tlv: [{ tag: 3, items: [{ id: 7 }] }] },
			{ name: '设置上报时间参数', func: '0x01', desc: 'Tag3-ID8 起始DD+hh+最大上报时长(预留) 见TLV',
				tlv: [{ tag: 3, items: [{ id: 8, value: [] }] }] },
			{ name: '设置上报重发次数', func: '0x01', desc: 'Tag3-ID10 上报重发次数 0-4',
				param: { label: '次数', type: 'uint8', default: '1' },
				tlv: [{ tag: 3, items: [{ id: 10 }] }] },
			{ name: '设置上报重发间隔', func: '0x01', desc: 'Tag3-ID11 上报重发间隔(分钟)',
				param: { label: '间隔(分钟)', type: 'uint8', default: '20' },
				tlv: [{ tag: 3, items: [{ id: 11 }] }] },
			{ name: '设置通信方式', func: '0x01', desc: 'Tag3-ID23 bit7-5运营商 bit4-0协议 见TLV',
				tlv: [{ tag: 3, items: [{ id: 23, value: [] }] }] },
			{ name: '设置上报定时点', func: '0x01', desc: 'Tag3-ID44 6组定时点(时+分各1B)共12B 见TLV',
				tlv: [{ tag: 3, items: [{ id: 44, value: [] }] }] },
		]
	},
	{
		group: '参数设置-维护平台配置 (0x01)',
		items: [
			{ name: '设置维护平台上报频率', func: '0x01', desc: 'Tag3-ID22 维护后台上报频率(分钟) 须1440整数倍',
				param: { label: '间隔(分钟)', type: 'uint16le', default: '1440' },
				tlv: [{ tag: 3, items: [{ id: 22 }] }] },
			{ name: '配置维护平台IP', func: '0x01', desc: 'Tag3-ID21 维护后台地址端口 ASCII 逗号分隔',
				param: { label: 'IP:端口', type: 'ascii', default: '', fillLen: 32 },
				tlv: [{ tag: 3, items: [{ id: 21 }] }] },
			{ name: '设置维护上报时间参数', func: '0x01', desc: 'Tag3-ID27 起始DD+hh+最大上报时长(预留) 见TLV',
				tlv: [{ tag: 3, items: [{ id: 27, value: [] }] }] },
			{ name: '设置维护平台连接模式', func: '0x01', desc: 'Tag3-ID40 维护平台连接模式',
				param: { label: '连接模式', type: 'enum', default: '0', options: { 0: 'IPV4', 1: 'IPV6' } },
				tlv: [{ tag: 3, items: [{ id: 40 }] }] },
		]
	},
	{
		group: '参数设置-告警阈值 (0x01)',
		items: [
			{ name: '设置过流告警阈值', func: '0x01', desc: 'Tag3-ID0 过流告警(L/h)',
				param: { label: '阈值(L/h)', type: 'uint32le', default: '3125' },
				tlv: [{ tag: 3, items: [{ id: 0 }] }] },
			{ name: '设置持续过流告警时间', func: '0x01', desc: 'Tag3-ID1 持续过流告警时间(分钟)',
				param: { label: '时间(分钟)', type: 'uint8', default: '30' },
				tlv: [{ tag: 3, items: [{ id: 1 }] }] },
			{ name: '设置反流告警阈值', func: '0x01', desc: 'Tag3-ID2 反流告警(L/h)',
				param: { label: '阈值(L/h)', type: 'uint32le', default: '40' },
				tlv: [{ tag: 3, items: [{ id: 2 }] }] },
			{ name: '设置持续反流告警时间', func: '0x01', desc: 'Tag3-ID3 持续反流告警时间(分钟)',
				param: { label: '时间(分钟)', type: 'uint8', default: '30' },
				tlv: [{ tag: 3, items: [{ id: 3 }] }] },
			{ name: '设置电压告警阈值', func: '0x01', desc: 'Tag3-ID4 电压告警阈值(0.01V)',
				param: { label: '阈值(0.01V)', type: 'uint16le', default: '0' },
				tlv: [{ tag: 3, items: [{ id: 4 }] }] },
			{ name: '设置即时告警ID', func: '0x01', desc: 'Tag3-ID5 16位位域(HEX) 见TLV编辑',
				tlv: [{ tag: 3, items: [{ id: 5, value: [] }] }] },
			{ name: '设置环境温度报警阈值', func: '0x01', desc: 'Tag3-ID33 低温+高温(℃) int8各1B 见TLV',
				tlv: [{ tag: 3, items: [{ id: 33, value: [] }] }] },
		]
	},
	{
		group: '参数设置-计量参数 (0x01)',
		items: [
			{ name: '设置计量底度', func: '0x01', desc: 'Tag3-ID17 计量底度(L)',
				param: { label: '底度(L)', type: 'uint32le', default: '0' },
				tlv: [{ tag: 3, items: [{ id: 17 }] }] },
			{ name: '设置计量底度正累积(大口径)', func: '0x01', desc: 'Tag3-ID35 大口径正累积底度 状态+7B值 见TLV',
				tlv: [{ tag: 3, items: [{ id: 35, value: [] }] }] },
			{ name: '设置计量底度逆累积(大口径)', func: '0x01', desc: 'Tag3-ID36 大口径逆累积底度 状态+7B值 见TLV',
				tlv: [{ tag: 3, items: [{ id: 36, value: [] }] }] },
			{ name: '设置水表口径', func: '0x01', desc: 'Tag3-ID18 水表口径',
				param: { label: '口径', type: 'enum', default: '5', options: { 1: '15mm', 2: '20mm', 3: '25mm', 4: '32mm', 5: '40mm', 6: '50mm', 7: '65mm', 8: '80mm', 9: '100mm', 10: '125mm', 11: '150mm', 12: '200mm', 13: '250mm', 14: '300mm' } },
				tlv: [{ tag: 3, items: [{ id: 18 }] }] },
			{ name: '设置采集方式', func: '0x01', desc: 'Tag3-ID24 采集方式',
				param: { label: '采集方式', type: 'enum', default: '5', options: { 0: '未知', 1: '数字状态', 2: '厚膜', 3: '光电', 4: '脉冲', 5: '无磁', 6: '超声波', 7: '电磁式', 8: '摄像', 9: '总线式', 10: '无磁摄像' } },
				tlv: [{ tag: 3, items: [{ id: 24 }] }] },
			{ name: '设置脉冲形式', func: '0x01', desc: 'Tag3-ID28 脉冲形式',
				param: { label: '脉冲形式', type: 'enum', default: '5', options: { 0: '未知', 1: '单脉冲', 2: '双脉冲', 3: '正反单脉冲', 4: '方向单脉冲', 5: 'HRI', 8: '三霍尔', 9: '双霍尔' } },
				tlv: [{ tag: 3, items: [{ id: 28 }] }] },
			{ name: '设置基准水量', func: '0x01', desc: 'Tag3-ID29 基准水量',
				param: { label: '基准水量', type: 'enum', default: '0', options: { 0: '1000L/圈', 1: '100L/圈', 2: '10L/圈', 3: '1L/圈' } },
				tlv: [{ tag: 3, items: [{ id: 29 }] }] },
			{ name: '设置基表整数位数', func: '0x01', desc: 'Tag3-ID30 基表整数位数',
				param: { label: '整数位数', type: 'uint8', default: '5' },
				tlv: [{ tag: 3, items: [{ id: 30 }] }] },
			{ name: '设置机电分离状态', func: '0x01', desc: 'Tag3-ID34 机电分离状态配置',
				param: { label: '分离状态', type: 'enum', default: '0', options: { 0: '未分离', 1: '机电分离' } },
				tlv: [{ tag: 3, items: [{ id: 34 }] }] },
			{ name: '设置计量模组开关', func: '0x01', desc: 'Tag3-ID38 计量模组启用',
				param: { label: '开关', type: 'enum', default: '1', options: { 0: '关闭', 1: '开启' } },
				tlv: [{ tag: 3, items: [{ id: 38 }] }] },
			{ name: '设置采样间隔', func: '0x01', desc: 'Tag3-ID12 数据采样间隔(分钟) 须30整数倍',
				param: { label: '间隔(分钟)', type: 'uint16le', default: '30' },
				tlv: [{ tag: 3, items: [{ id: 12 }] }] },
			{ name: '设置密集采样起始时间', func: '0x01', desc: 'Tag3-ID14 密集数据采样起始时间(小时)',
				param: { label: '小时(0-23)', type: 'uint8', default: '0' },
				tlv: [{ tag: 3, items: [{ id: 14 }] }] },
			{ name: '设置密集采样间隔', func: '0x01', desc: 'Tag3-ID15 密集数据采样间隔(分钟) 须5整数倍',
				param: { label: '间隔(分钟)', type: 'uint8', default: '5' },
				tlv: [{ tag: 3, items: [{ id: 15 }] }] },
			{ name: '设置用水量功能超时', func: '0x01', desc: 'Tag3-ID41 用水量功能超时时间(秒) 0关闭',
				param: { label: '超时(秒)', type: 'uint16le', default: '0' },
				tlv: [{ tag: 3, items: [{ id: 41 }] }] },
		]
	},
	{
		group: '参数设置-设备标识 (0x01)',
		items: [
			{ name: '设置用户表号', func: '0x01', desc: 'Tag3-ID19 用户表号 BCD小端 10B',
				param: { label: '表号(纯数字)', type: 'bcd', default: '', fillLen: 10 },
				tlv: [{ tag: 3, items: [{ id: 19 }] }] },
			{ name: '设置基表号', func: '0x01', desc: 'Tag3-ID26 基表号 BCD小端 10B',
				param: { label: '基表号(纯数字)', type: 'bcd', default: '', fillLen: 10 },
				tlv: [{ tag: 3, items: [{ id: 26 }] }] },
			{ name: '设置设备唯一编码', func: '0x01', desc: 'Tag3-ID25 设备唯一编码 BCD小端 7B',
				param: { label: '唯一编码(纯数字)', type: 'bcd', default: '', fillLen: 7 },
				tlv: [{ tag: 3, items: [{ id: 25 }] }] },
			{ name: '设置SN密钥', func: '0x01', desc: 'Tag3-ID16 SN密钥 16字节ASCII',
				param: { label: 'SN密钥', type: 'ascii', default: '', fillLen: 16 },
				tlv: [{ tag: 3, items: [{ id: 16 }] }] },
		]
	},
	{
		group: '参数设置-设备管理 (0x01)',
		items: [
			{ name: '设置设备启用标志', func: '0x01', desc: 'Tag3-ID31 启用标志',
				param: { label: '启用标志', type: 'enum', default: '1', options: { 0: '停止', 1: '启用', 2: '运输模式' } },
				tlv: [{ tag: 3, items: [{ id: 31 }] }] },
			{ name: '设置设备校时类型', func: '0x01', desc: 'Tag3-ID32 校时类型',
				param: { label: '校时类型', type: 'enum', default: '1', options: { 0: '基站校时', 1: '服务器校时' } },
				tlv: [{ tag: 3, items: [{ id: 32 }] }] },
			{ name: '设置电池参数', func: '0x01', desc: 'Tag3-ID39 总容量+起始容量 uint16各2B 见TLV',
				tlv: [{ tag: 3, items: [{ id: 39, value: [] }] }] },
			{ name: '设置结算日参数', func: '0x01', desc: 'Tag3-ID13 起始日+结算日间隔(天) 各1B 见TLV',
				tlv: [{ tag: 3, items: [{ id: 13, value: [] }] }] },
			{ name: '设置水表实时时间', func: '0x01', desc: 'Tag3-ID20 水表时间 BCD YYYYMMDDhhmmss 见TLV',
				tlv: [{ tag: 3, items: [{ id: 20, value: [] }] }] },
		]
	},
	{
		group: '参数设置-TAG32摄像表 (0x01)',
		items: [
			{ name: '设置坐标', func: '0x01', desc: 'Tag32-ID1 Y X1-X8 各16bit LE 共18B 见TLV',
				tlv: [{ tag: 32, items: [{ id: 1, value: [] }] }] },
			{ name: '设置字轮宽', func: '0x01', desc: 'Tag32-ID2 字轮宽 0-25',
				param: { label: '宽度', type: 'uint16le', default: '0' },
				tlv: [{ tag: 32, items: [{ id: 2 }] }] },
			{ name: '设置字轮高', func: '0x01', desc: 'Tag32-ID3 字轮高 0-36',
				param: { label: '高度', type: 'uint16le', default: '0' },
				tlv: [{ tag: 32, items: [{ id: 3 }] }] },
			{ name: '设置字轮半高', func: '0x01', desc: 'Tag32-ID4 半字时高度 0-36',
				param: { label: '半高', type: 'uint16le', default: '0' },
				tlv: [{ tag: 32, items: [{ id: 4 }] }] },
			{ name: '设置模板半高', func: '0x01', desc: 'Tag32-ID5 模板半字高度 0-36',
				param: { label: '模板半高', type: 'uint16le', default: '0' },
				tlv: [{ tag: 32, items: [{ id: 5 }] }] },
			{ name: '设置字轮数', func: '0x01', desc: 'Tag32-ID6 字轮个数 0-8 默认5',
				param: { label: '字轮数', type: 'uint8', default: '5' },
				tlv: [{ tag: 32, items: [{ id: 6 }] }] },
			{ name: '设置二值化系数', func: '0x01', desc: 'Tag32-ID7 二值化系数 0-100 默认20',
				param: { label: '系数(0-100)', type: 'uint8', default: '20' },
				tlv: [{ tag: 32, items: [{ id: 7 }] }] },
			{ name: '设置代码段', func: '0x01', desc: 'Tag32-ID8 字轮模板类型 0-16',
				param: { label: '代码段', type: 'uint8', default: '0' },
				tlv: [{ tag: 32, items: [{ id: 8 }] }] },
			{ name: '设置灰度图片坐标', func: '0x01', desc: 'Tag32-ID9 相对Y坐标 0-480',
				param: { label: 'Y坐标', type: 'uint16le', default: '0' },
				tlv: [{ tag: 32, items: [{ id: 9 }] }] },
			{ name: '设置图像格式', func: '0x01', desc: 'Tag32-ID10 bit3-0格式 bit7需识别 bit6旋转 见TLV',
				tlv: [{ tag: 32, items: [{ id: 10, value: [] }] }] },
			{ name: '设置图像品质', func: '0x01', desc: 'Tag32-ID11 压缩系数 0-100',
				param: { label: '品质(0-100)', type: 'uint8', default: '50' },
				tlv: [{ tag: 32, items: [{ id: 11 }] }] },
			{ name: '设置数据差值', func: '0x01', desc: 'Tag32-ID13 16位有符号 -32768~32767L',
				param: { label: '差值(L)', type: 'uint16le', default: '0' },
				tlv: [{ tag: 32, items: [{ id: 13 }] }] },
			{ name: '设置相对坐标X', func: '0x01', desc: 'Tag32-ID15 灰度图片相对X 0-1600',
				param: { label: 'X坐标', type: 'uint16le', default: '0' },
				tlv: [{ tag: 32, items: [{ id: 15 }] }] },
			{ name: '设置闪光灯强度', func: '0x01', desc: 'Tag32-ID16 0左边 1右边 2全开',
				param: { label: '闪光灯', type: 'enum', default: '0', options: { 0: '左边', 1: '右边', 2: '全开' } },
				tlv: [{ tag: 32, items: [{ id: 16 }] }] },
			{ name: '设置图片上传间隔', func: '0x01', desc: 'Tag32-ID17 分钟 0不上报 须1440整数倍',
				param: { label: '间隔(分钟)', type: 'uint16le', default: '0' },
				tlv: [{ tag: 32, items: [{ id: 17 }] }] },
			{ name: '设置图片旋转角度', func: '0x01', desc: 'Tag32-ID18 旋转角度(度)',
				param: { label: '角度(度)', type: 'uint8', default: '0' },
				tlv: [{ tag: 32, items: [{ id: 18 }] }] },
		]
	},
	{
		group: '参数设置-TAG33总线采集器 (0x01)',
		items: [
			{ name: '设置总线表组', func: '0x01', desc: 'Tag33-ID0 总线表组 默认0',
				param: { label: '组号', type: 'uint8', default: '0' },
				tlv: [{ tag: 33, items: [{ id: 0 }] }] },
			{ name: '设置总线表地址1', func: '0x01', desc: 'Tag33-ID1 地址BCD小端 7B 0/全FF删除 见TLV',
				tlv: [{ tag: 33, items: [{ id: 1, value: [] }] }] },
			{ name: '设置抄表日期(旧)', func: '0x01', desc: 'Tag33-ID21 BYTE[N]=1表示日期N需抄表 32B 见TLV',
				tlv: [{ tag: 33, items: [{ id: 21, value: [] }] }] },
			{ name: '设置抄表定时点', func: '0x01', desc: 'Tag33-ID22 0-23时',
				param: { label: '定时点(时)', type: 'uint8', default: '0' },
				tlv: [{ tag: 33, items: [{ id: 22 }] }] },
			{ name: '设置启动延时', func: '0x01', desc: 'Tag33-ID23 0-10秒',
				param: { label: '延时(秒)', type: 'uint8', default: '0' },
				tlv: [{ tag: 33, items: [{ id: 23 }] }] },
			{ name: '设置抄表时长', func: '0x01', desc: 'Tag33-ID24 0-20秒',
				param: { label: '时长(秒)', type: 'uint8', default: '0' },
				tlv: [{ tag: 33, items: [{ id: 24 }] }] },
			{ name: '设置总线表集抄', func: '0x01', desc: 'Tag33-ID25 0停止 1开始集抄',
				param: { label: '集抄', type: 'enum', default: '0', options: { 0: '停止', 1: '开始集抄' } },
				tlv: [{ tag: 33, items: [{ id: 25 }] }] },
			{ name: '设置抄表日期', func: '0x01', desc: 'Tag33-ID27 bit1-31表示日期需抄表 4B位域 见TLV',
				tlv: [{ tag: 33, items: [{ id: 27, value: [] }] }] },
			{ name: '设置周期数据上报方式', func: '0x01', desc: 'Tag33-ID29 0x90=tag90 0x94=tag94',
				param: { label: '上报方式', type: 'enum', default: '90', options: { 90: 'tag90上报', 148: 'tag94上报' } },
				tlv: [{ tag: 33, items: [{ id: 29 }] }] },
			{ name: '设置485总线协议ID', func: '0x01', desc: 'Tag33-ID30 0-255',
				param: { label: '协议ID', type: 'uint8', default: '0' },
				tlv: [{ tag: 33, items: [{ id: 30 }] }] },
			{ name: '设置485串口参数', func: '0x01', desc: 'Tag33-ID31 bit6数据位/bit5停止位/bit4-3校验/bit2-0波特率 见TLV',
				tlv: [{ tag: 33, items: [{ id: 31, value: [] }] }] },
			{ name: '设置数据类型上报开关', func: '0x01', desc: 'Tag33-ID32 32bit位域 BIT0-13各数据 见TLV',
				tlv: [{ tag: 33, items: [{ id: 32, value: [] }] }] },
		]
	},
	{
		group: '参数设置-TAG34无磁传感器 (0x01)',
		items: [
			{ name: '设置计量过滤模式', func: '0x01', desc: 'Tag34-ID2 计量过滤模式',
				param: { label: '过滤模式', type: 'enum', default: '0', options: { 0: '常规', 1: '开猫16ms滤波', 2: '开猫32ms滤波', 3: '开猫不计量' } },
				tlv: [{ tag: 34, items: [{ id: 2 }] }] },
			{ name: '设置SENSOR参数', func: '0x01', desc: 'Tag34-ID3 BADJ1+BAJD2+采样周期+预留+测量时长 6B 见TLV',
				tlv: [{ tag: 34, items: [{ id: 3, value: [] }] }] },
			{ name: '设置采样距离', func: '0x01', desc: 'Tag34-ID5 采样距离(mm)',
				param: { label: '距离(mm)', type: 'uint8', default: '0' },
				tlv: [{ tag: 34, items: [{ id: 5 }] }] },
			{ name: '设置采样频率', func: '0x01', desc: 'Tag34-ID6 采样频率(ms)',
				param: { label: '频率(ms)', type: 'uint8', default: '0' },
				tlv: [{ tag: 34, items: [{ id: 6 }] }] },
		]
	},
	{
		group: '参数设置-TAG35LoRa (0x01)',
		items: [
			{ name: '设置网络频率', func: '0x01', desc: 'Tag35-ID1 KHz 高字节在前 3B 如485MHz=07 66 88 见TLV',
				tlv: [{ tag: 35, items: [{ id: 1, value: [] }] }] },
			{ name: '设置设备逻辑地址', func: '0x01', desc: 'Tag35-ID2 4字节无线逻辑地址 见TLV',
				tlv: [{ tag: 35, items: [{ id: 2, value: [] }] }] },
			{ name: '设置网络ID', func: '0x01', desc: 'Tag35-ID3 2字节网络ID高字节在前 见TLV',
				tlv: [{ tag: 35, items: [{ id: 3, value: [] }] }] },
			{ name: '设置参数配置', func: '0x01', desc: 'Tag35-ID4 8B:第三方抄表+低压关阀+除锈+通信时间 见TLV',
				tlv: [{ tag: 35, items: [{ id: 4, value: [] }] }] },
		]
	},
	{
		group: '参数设置-TAG36阀控 (0x01)',
		items: [
			{ name: '设置阀门自检日', func: '0x01', desc: 'Tag36-ID1 天 0-31 默认15',
				param: { label: '自检日', type: 'uint8', default: '15' },
				tlv: [{ tag: 36, items: [{ id: 1 }] }] },
			{ name: '设置关阀高频上报频率', func: '0x01', desc: 'Tag36-ID2 小时 1-24 默认2',
				param: { label: '频率(小时)', type: 'uint8', default: '2' },
				tlv: [{ tag: 36, items: [{ id: 2 }] }] },
			{ name: '设置关阀高频上报周期', func: '0x01', desc: 'Tag36-ID3 天 1-30 默认3',
				param: { label: '周期(天)', type: 'uint8', default: '3' },
				tlv: [{ tag: 36, items: [{ id: 3 }] }] },
			{ name: '设置应急开阀周期', func: '0x01', desc: 'Tag36-ID4 小时 1-72 默认24',
				param: { label: '周期(小时)', type: 'uint8', default: '24' },
				tlv: [{ tag: 36, items: [{ id: 4 }] }] },
			{ name: '设置应急开阀次数', func: '0x01', desc: 'Tag36-ID5 次 1-3 默认1',
				param: { label: '次数', type: 'uint8', default: '1' },
				tlv: [{ tag: 36, items: [{ id: 5 }] }] },
			{ name: '设置应急开阀功能', func: '0x01', desc: 'Tag36-ID6 1使能 0不使能 默认1',
				param: { label: '应急开阀', type: 'enum', default: '1', options: { 0: '不使能', 1: '使能' } },
				tlv: [{ tag: 36, items: [{ id: 6 }] }] },
			{ name: '设置低电压关阀功能', func: '0x01', desc: 'Tag36-ID7 1使能 0不使能 默认0',
				param: { label: '低电压关阀', type: 'enum', default: '0', options: { 0: '不使能', 1: '使能' } },
				tlv: [{ tag: 36, items: [{ id: 7 }] }] },
			{ name: '设置低电压关阀周期', func: '0x01', desc: 'Tag36-ID8 天 1-45 默认30',
				param: { label: '周期(天)', type: 'uint8', default: '30' },
				tlv: [{ tag: 36, items: [{ id: 8 }] }] },
			{ name: '设置磁干扰关阀功能', func: '0x01', desc: 'Tag36-ID9 1使能 0不使能 默认1',
				param: { label: '磁干扰关阀', type: 'enum', default: '1', options: { 0: '不使能', 1: '使能' } },
				tlv: [{ tag: 36, items: [{ id: 9 }] }] },
			{ name: '设置磁干扰关阀周期', func: '0x01', desc: 'Tag36-ID10 天 1-15 默认7',
				param: { label: '周期(天)', type: 'uint8', default: '7' },
				tlv: [{ tag: 36, items: [{ id: 10 }] }] },
			{ name: '设置关阀高频上报起止时间', func: '0x01', desc: 'Tag36-ID11 起始时+结束时 默认6-18 见TLV',
				tlv: [{ tag: 36, items: [{ id: 11, value: [] }] }] },
			{ name: '设置开度调整时间参数', func: '0x01', desc: 'Tag36-ID12 频率天+4时段(起hh起mm开度) 16B 见TLV',
				tlv: [{ tag: 36, items: [{ id: 12, value: [] }] }] },
			{ name: '设置阀控功能开关', func: '0x01', desc: 'Tag36-ID13 1开启 0关闭 默认1',
				param: { label: '阀控功能', type: 'enum', default: '1', options: { 0: '关闭', 1: '开启' } },
				tlv: [{ tag: 36, items: [{ id: 13 }] }] },
			{ name: '设置应急开阀限定用水量', func: '0x01', desc: 'Tag36-ID14 单位10L',
				param: { label: '用水量(10L)', type: 'uint16le', default: '0' },
				tlv: [{ tag: 36, items: [{ id: 14 }] }] },
		]
	},
	{
		group: '参数设置-TAG37蓝牙 (0x01)',
		items: [
			{ name: '设置蓝牙表名称', func: '0x01', desc: 'Tag37-ID0 蓝牙名称 ASCII 16B',
				param: { label: '名称', type: 'ascii', default: '', fillLen: 16 },
				tlv: [{ tag: 37, items: [{ id: 0 }] }] },
			{ name: '设置蓝牙表广播功能', func: '0x01', desc: 'Tag37-ID1 0关闭 1开启',
				param: { label: '广播', type: 'enum', default: '1', options: { 0: '关闭', 1: '开启' } },
				tlv: [{ tag: 37, items: [{ id: 1 }] }] },
			{ name: '设置蓝牙检索功能', func: '0x01', desc: 'Tag37-ID2 0默认检索 其他预留',
				param: { label: '检索模式', type: 'uint8', default: '0' },
				tlv: [{ tag: 37, items: [{ id: 2 }] }] },
			{ name: '设置蓝牙检索MAC', func: '0x01', desc: 'Tag37-ID3 检索蓝牙MAC 6B 见TLV',
				tlv: [{ tag: 37, items: [{ id: 3, value: [] }] }] },
			{ name: '设置蓝牙分体阀表号', func: '0x01', desc: 'Tag37-ID4 BCD小端 10B',
				param: { label: '表号(纯数字)', type: 'bcd', default: '', fillLen: 10 },
				tlv: [{ tag: 37, items: [{ id: 4 }] }] },
		]
	},
	{
		group: '参数设置-TAG38通讯认证 (0x01)',
		items: [
			{ name: '设置加密方式', func: '0x01', desc: 'Tag38-ID0 0不加密 1AES128 2AES256',
				param: { label: '加密方式', type: 'enum', default: '0', options: { 0: '不加密', 1: 'AES128', 2: 'AES256' } },
				tlv: [{ tag: 38, items: [{ id: 0 }] }] },
			{ name: '设置密钥Key', func: '0x01', desc: 'Tag38-ID1 通信密钥 32B AES128前16B 见TLV',
				tlv: [{ tag: 38, items: [{ id: 1, value: [] }] }] },
			{ name: '设置填充方式', func: '0x01', desc: 'Tag38-ID2 0不填充',
				param: { label: '填充方式', type: 'enum', default: '0', options: { 0: '不填充' } },
				tlv: [{ tag: 38, items: [{ id: 2 }] }] },
			{ name: '设置密码工作模式', func: '0x01', desc: 'Tag38-ID3 0 ECB',
				param: { label: '工作模式', type: 'enum', default: '0', options: { 0: 'ECB' } },
				tlv: [{ tag: 38, items: [{ id: 3 }] }] },
			{ name: '设置用户账号', func: '0x01', desc: 'Tag38-ID4 用户账号 char[32]',
				param: { label: '账号', type: 'ascii', default: '', fillLen: 32 },
				tlv: [{ tag: 38, items: [{ id: 4 }] }] },
			{ name: '设置用户密码', func: '0x01', desc: 'Tag38-ID5 用户密码 char[32]',
				param: { label: '密码', type: 'ascii', default: '', fillLen: 32 },
				tlv: [{ tag: 38, items: [{ id: 5 }] }] },
			{ name: '设置动态密钥加密功能', func: '0x01', desc: 'Tag38-ID6 0不使能 1使能',
				param: { label: '动态密钥', type: 'enum', default: '0', options: { 0: '不使能', 1: '使能' } },
				tlv: [{ tag: 38, items: [{ id: 6 }] }] },
		]
	},
	{
		group: '参数设置-TAG39告警 (0x01)',
		items: [
			{ name: '设置突发大用水告警参数', func: '0x01', desc: 'Tag39-ID1 使能1B+持续时间2B(M)+阈值4B(L)+判断阈值1B(L) 见TLV',
				tlv: [{ tag: 39, items: [{ id: 1, value: [] }] }] },
			{ name: '设置分时段低流量告警参数', func: '0x01', desc: 'Tag39-ID2 使能1B+4分段(起止2B+流量4B) 见TLV',
				tlv: [{ tag: 39, items: [{ id: 2, value: [] }] }] },
			{ name: '设置持续小流量告警参数', func: '0x01', desc: 'Tag39-ID3 持续时间2B(min)+流量阈值2B(L) 见TLV',
				tlv: [{ tag: 39, items: [{ id: 3, value: [] }] }] },
		]
	},
	{
		group: '指令操作 (0x11)',
		items: [
			{ name: '开业务猫', func: '0x11', desc: 'Tag93 开猫 仅业务',
				tlv: [{ tag: 93, items: [{ id: 0, value: [0x01] }] }] },
			{ name: '开维护猫', func: '0x11', desc: 'Tag93 开猫 仅维护',
				tlv: [{ tag: 93, items: [{ id: 0, value: [0x02] }] }] },
			{ name: '双开猫', func: '0x11', desc: 'Tag93 开猫 业务+维护',
				tlv: [{ tag: 93, items: [{ id: 0, value: [0x03] }] }] },
			{ name: '开阀', func: '0x11', desc: 'Tag93 阀门控制 开阀',
				tlv: [{ tag: 93, items: [{ id: 3, value: [0x01] }] }] },
			{ name: '关阀', func: '0x11', desc: 'Tag93 阀门控制 关阀',
				tlv: [{ tag: 93, items: [{ id: 3, value: [0x00] }] }] },
			{ name: '设备复位', func: '0x11', desc: 'Tag93 复位',
				param: { label: '延时(秒)', type: 'uint8', default: '2' },
				tlv: [{ tag: 93, items: [{ id: 1 }] }] },
			{ name: '初始化', func: '0x11', desc: 'Tag93 初始化(协议0-3; FlowLogic C 现为1-4请按设备确认)',
				param: { label: '初始化类型', type: 'enum', default: '0', options: { 0: '数据初始化', 1: '参数初始化', 2: '恢复出厂', 3: '信息初始化' } },
				tlv: [{ tag: 93, items: [{ id: 2 }] }] },
			{ name: '总线表阀门控制', func: '0x11', desc: 'Tag93-ID10 总线表阀门(详见TLV)',
				tlv: [{ tag: 93, items: [{ id: 10, value: [] }] }] },
			{ name: '阀门开阀度控制', func: '0x11', desc: 'Tag93-ID17 开阀度0-100',
				param: { label: '开阀度(0-100)', type: 'uint8', default: '100' },
				tlv: [{ tag: 93, items: [{ id: 17 }] }] },
			{ name: '休眠', func: '0x11', desc: 'Tag93-ID12 整机休眠',
				tlv: [{ tag: 93, items: [{ id: 12, value: [0x01] }] }] },
		]
	},
	{
		group: '信息查询 (0x03)',
		items: [
			{ name: '查询基础数据', func: '0x03', desc: 'Tag1 基础数据',
				tlv: [{ tag: 10, items: [{ id: 1 }] }] },
			{ name: '查询核心数据', func: '0x03', desc: 'Tag2 核心数据',
				tlv: [{ tag: 10, items: [{ id: 2 }] }] },
			{ name: '查询终端参数', func: '0x03', desc: 'Tag3 终端参数',
				tlv: [{ tag: 10, items: [{ id: 3 }] }] },
			{ name: '查询告警数据', func: '0x03', desc: 'Tag4 告警数据',
				tlv: [{ tag: 10, items: [{ id: 4 }] }] },
			{ name: '查询无磁传感器参数', func: '0x03', desc: 'Tag34 无磁传感器',
				tlv: [{ tag: 10, items: [{ id: 13 }] }] },
			{ name: '查询超声波表参数', func: '0x03', desc: 'Tag30 超声波表',
				tlv: [{ tag: 10, items: [{ id: 30 }] }] },
			{ name: '查询超声波表状态参数', func: '0x03', desc: 'Tag31 超声波状态',
				tlv: [{ tag: 10, items: [{ id: 31 }] }] },
			{ name: '查询阀控参数', func: '0x03', desc: 'Tag36 阀控',
				tlv: [{ tag: 10, items: [{ id: 15 }] }] },
			{ name: '查询通信认证参数', func: '0x03', desc: 'Tag38 通信认证',
				tlv: [{ tag: 10, items: [{ id: 22 }] }] },
			{ name: '查询设备运行信息', func: '0x03', desc: 'Tag91 运行信息',
				tlv: [{ tag: 10, items: [{ id: 7 }] }] },
			{ name: '查询设备上行信息', func: '0x03', desc: 'Tag92 上行信息',
				tlv: [{ tag: 10, items: [{ id: 8 }] }] },
			{ name: '查询日结数据', func: '0x03', desc: 'Tag10-ID9 起始日YYMMDD(BCD)+个数',
				param: { label: '个数', type: 'dailyQuery', default: '7' },
				tlv: [{ tag: 10, items: [{ id: 9 }] }] },
			{ name: '查询错误日志', func: '0x03', desc: 'Tag10-ID23 起始时间6B BCD+条数',
				param: { label: '条数', type: 'errLogQuery', default: '4' },
				tlv: [{ tag: 10, items: [{ id: 23 }] }] },
			{ name: '查询摄像表参数', func: '0x03', desc: 'Tag32 摄像表',
				tlv: [{ tag: 10, items: [{ id: 10 }] }] },
			{ name: '查询总线采集器参数', func: '0x03', desc: 'Tag33 总线采集器',
				tlv: [{ tag: 10, items: [{ id: 11 }] }] },
			{ name: '查询蓝牙表参数', func: '0x03', desc: 'Tag37 蓝牙',
				tlv: [{ tag: 10, items: [{ id: 18 }] }] },
			{ name: '查询指定ID数据', func: '0x03', desc: 'Tag10-ID0 2B一组(tag+id) 共16组 见TLV',
				tlv: [{ tag: 10, items: [{ id: 0, value: [] }] }] },
			{ name: '查询历史冻结数据', func: '0x03', desc: 'Tag10-ID24 0=前30日 1=31-60日',
				param: { label: '范围(0/1)', type: 'uint8', default: '0' },
				tlv: [{ tag: 10, items: [{ id: 24 }] }] },
		]
	},
]
